#!/usr/bin/env python3

print("*" * 50)
print("Doctor Who Festival - Price Calculator")
print("*" * 50)

print("Note: Enter 0 if none:")
print("Prices for Individual: £68 \n16s: £32.25 \nFamilies: £42.75")
indi = int(input("Enter total number of individuals: "))
under = int(input("Enter total number of under 16s: "))
fam = int(input("Enter total number of families: "))
print("*" * 50)
print("Category Price Breakdown")
print("*" * 50)
indi_2 = float(indi * 68)
under_2 = float(under * 32.25)
fam_2 = float(fam * 42.75)
print("Price is £%.2f for %d individuals"%(indi_2, indi))
print("Price is £%.2f for %d under 16s"%(under_2, under))
print("Price is £%.2f for %d families"%(fam_2, fam))
print("*" * 50)
total_p = float(indi + fam)
total_m = float(indi_2 + under_2 + fam_2)
print("Total Persons are %d"%(total_p))
print("Total Event Price is £%.2f"%(total_m))
print("More info and booking visit our website https://www.aarif.co.uk")
